name: flask
type: service
from: python
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.1"
title: Python (Flask)
labels:
- flask
- python

env:
- name: GUNICORN_APP
  value: app:app
- name: FLASK_DEBUG
  value: 'true'
  envType: dev

build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: flask
    title: Flask boilerplate
    repo: https://github.com/wodby/flask-boilerplate
    branch: main
